export enum MergeModeEnum {
    NO_RESTRICTIONS=0, // IT MEANS THAT IF WE HAVE THIS FIELD IN CHANGES, WE DO NOT CARE WHEN IT WAS UPDATED. WE ONLY NEED TO KNOW THAT IT WAS CHANGED AND THEN THE CHANGE WILL OCCUR.
    NEWER_CHANGES=1, // IT MEANS DA IF FIELD IS IN CHANGES, CHECK IN `RECORD` FROM BE IF `UPDATED_AT` IS BIGGER/HIGHER/LARGER THAN VALUE FROM SENT CHANGES
    DEFAULT=3, // @TODO
    USER_INTERACTION_NEEDED=4,
    NONE=5 // NEED TO ADD SOME DESCRIPTION IN CONFIGURATION TO INDICATED WHAT TO-DO IN CASE OF `NONE` (CURRENTLY THERE IS NO SPECIFIC PLAN FOR THIS IMPLEMENTATION)
}