export enum MergeModeEnum {
    NO_RESTRICTIONS=0, // POMENI, DA CE IMAMO V SPREMEMBAH TA FIELD, NAS NE ZANIMA KDAJ JE BIL POSODOBLJEN. CE PISE DA JE SPREMENJEN GA SPREMENI
    NEWER_CHANGES=1, // POMENI, DA CE JE FIELD V SPREMEMBAH, MORAS PREVERITI ALI IMA `RECORD` IZ `BE` VECJI `UPDATED_AT` KOT SPREMEMBA 
    DEFAULT=3, // @TODO
    USER_INTERACTION_NEEDED=4,
    NONE=5 // POTREBNO DODATI NEK ZAPIS V KONFIGURACIJO KJER BO POVEDALO, KAJ NAREDITI V PRIMERU `NONE` (MOGOCE JE TA OPCIJA IDENTICNA KOT OPCIJA `DEFAULT`).
}