conflict_field_groups:
    TestEntity:
        groups:
            -   
                field_name: 'first_input'
                merge_resolution: 2 # accept all === no restrictions
#                merge_resolution: 4 # conflict resolution
    TheTest:
        groups:
            -
                field_name: 'last_modified'
                merge_resolution: 4
            -
                field_name: 'name'
                merge_resolution: 4 # no restrictions
    entity_name:
        groups:
            -
                field_name: 'field1'
                merge_resolution: 2  # prej bila vrednost 3
            -
                field_name: 'field3'
                merge_resolution: 1  # default === no restrictions
            -   
                field_name: 'field4'
                merge_resolution: 3  # older changes not acceptable
    testing_example:
        groups:
            -
                field_name: 'f1'
                merge_resolution: 2
default_merge_resolution: 2 # Ce pride do spremembe takoj uveljavi spremembe - brez pomisleka
