#nelmio_cors:
#    defaults:
#        origin_regex: true
#        allow_origin: ['^(https|http)?://(localhost|127\.0\.0\.1)(:[0-9]+)?$']
##        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#        allow_methods: ['GET', 'OPTIONS', 'POST']
##        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#        allow_headers: ['*']
##        allow_headers: ['Content-Type', 'Authorization']
##        expose_headers: ['Link']
#        max_age: 3600
##    paths:
##        '^/':
##            origin_regex: true
##            allow_origin: ['^(https|http)?://(localhost|127\.0\.0\.1)(:[0-9]+)?$']
##            allow_headers: ['*']
##            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
            hosts: ['^api\.']
