export enum SyncEntityStatusEnum {
    SUCCESS = 'SUCCESS',
    MISSING_REQUIRED_FIELDS = 'MISSING_REQUIRED_FIELDS',
    SYNCHRONIZATION_LAST_MODIFIED_FIELD_MISMATCH = 'SYNCHRONIZATION_LAST_MODIFIED_FIELD_MISMATCH',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    REPOSITORY_NOT_FOUND = 'REPOSITORY_NOT_FOUND',
    ENTITY_DOES_NOT_EXIST = 'ENTITY_DOES_NOT_EXIST',
    CONFLICT = 'CONFLICT',
    MISSING_UUID_DATA = 'MISSING_UUID_DATA',
    UNSUCCESSFUL_SAVE_TO_DB = 'UNSUCCESSFUL_SAVE_TO_DB',
}